- name: 'Create environment'
  hosts: localhost
  tasks:
    - name: 'Get user ID'
      when: ansible_os_family != "Windows"
      command: id -u
      register: CUREENT_USER_ID
#    - name: 'Get user group'
#      when: ansible_os_family != "Windows"
#      command: id -g
#      register: CUREENT_GROUP_ID
    # Gather facts
    - name: 'Include global vars'
      include_vars:
        dir: ./../vars/global
    - name: 'Include environment vars'
      include_vars:
        dir: ./../vars/{{ env }}

    # Generate docker-compose files
    - name: 'Create docker-compose.yml file'
      template:
        src: ./../templates/docker/docker-compose.yml.j2
        dest: ./../../docker-compose.yml
        force: true
    - name: 'Create docker .env file'
      template:
        src: ./../templates/docker/{{ env }}-docker.env.j2
        dest: ./../../.env
        force: true
    - name: 'Replace docker .env file for Windows'
      when: ansible_os_family == "Windows"
      lineinfile:
        path: ./../../.env
        regexp: "^COMPOSE_PATH_SEPARATOR=:"
        line: "COMPOSE_PATH_SEPARATOR=;"

    # Generate config files of docker containers
    # TODO: Add generation of apache2 conf files
    # TODO: Add generation of ssl files
    - name: 'Create web server config file'
      when: WEBSERVER_TYPE == 'nginx'
      template:
        src: ./../templates/{{ WEBSERVER_TYPE }}/{{ env }}-default.conf
        dest: ./../../services/{{ WEBSERVER_TYPE }}/sites/default.conf
        force: true
    - name: 'Create workspace cron config file'
      template:
        src: ./../templates/workspace/{{ env }}-laradock.j2
        dest: ./../../services/workspace/crontab/laradock
        force: true
    - name: 'Create php worker config files'
      when: ENABLE_PHP_WORKER
      template:
        src: ./../templates/supervisor/{{ env }}-queue.conf
        dest: ./../../services/php-worker/supervisord.d/queue.conf
        force: true
    - name: 'Create sphinx.conf file'
      when: ENABLE_SPHINXSEARCH
      template:
        src: ./../templates/sphinxsearch/sphinx.conf
        dest: ./../../services/sphinxsearch/sphinx.conf
        force: true
    - name: 'Create config.php for beanstalkd-console'
      when: ENABLE_BEANSTALKD
      template:
        src: ./../templates/beanstalkd-console/{{ env }}-config.php
        dest: ./../../services/beanstalkd-console/config.php
        force: true

    # Generate app files
    - name: 'Create .htaccess file'
      when: WEBSERVER_TYPE == 'apache2'
      template:
        src: ./../templates/apache2/{{ env }}-htaccess.j2
        dest: ./../../app/.htaccess
        force: true
    - name: 'Create .env file in app folder'
      template:
        src: ./../templates/app/{{ env }}.env
        dest: ./../../app/.env
        force: true
    - name: 'Create laravel-echo-server.json file in services/laravel-echo-server folder'
      template:
        src: ./../templates/laravel-echo/{{ env }}-laravel-echo-server.json
        dest: ./../../services/laravel-echo-server/laravel-echo-server.json
        force: true
    - name: 'Copy robots.txt file in app folder'
      template:
        src: ./../templates/app/{{ env }}-robots.txt
        dest: ./../../app/robots.txt
        force: true